# ----------------------------------------------------------------------------
#
# Package             : k8s-kubectl
# Source Repo         : https://github.com/lachie83/k8s-kubectl
# Travis Job Link     : https://travis-ci.com/github/asellappen/k8s-kubectl/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: required
arch:
  - amd64
  - ppc64le

language: ruby

before_install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
  - sudo apt-get install rake
  
trigger:
- main
- v*

steps:
- script: GIT_BRANCH=$(build.SourceBranchName) make docker_build
  displayName: 'Build kubectl container'
- script: GIT_BRANCH=$(build.SourceBranchName) make test
  displayName: 'Test kubectl container'
- script: |
    docker login -u $(dockerId) -p $(pswd)
    GIT_BRANCH=$(build.SourceBranchName) make docker_push
  condition: or(startsWith(variables['Build.SourceBranchName'], 'v'), startsWith(variables['Build.SourceBranchName'], 'main'))
  displayName: 'Publish kubectl container'
