arch:
  - amd64
  - ppc64le

steps:
- script: GIT_BRANCH=$(build.SourceBranchName) make docker_build
  displayName: 'Build kubectl container'
- script: GIT_BRANCH=$(build.SourceBranchName) make test
  displayName: 'Test kubectl container'
- script: |
    docker login -u $(dockerId) -p $(pswd)
    GIT_BRANCH=$(build.SourceBranchName) make docker_push
  condition: or(startsWith(variables['Build.SourceBranchName'], 'v'), startsWith(variables['Build.SourceBranchName'], 'main'))
  displayName: 'Publish kubectl container'
